public class Example1
{
    public static void main(String[] args)
    {
        int     denominator, numerator, ratio;


        numerator   = 5;
        denominator = 1;  //denominator = 2;


//        try{
//            ratio = numerator/denominator;
//        }
//        catch(ArithmeticException e){
//
//        }



        try{
            ratio = numerator/denominator;
            System.out.println("The answer is: " + ratio);
            System.out.println("Done");
        }
        catch(ArithmeticException e){
            System.out.println("Divide by 0");
            e.printStackTrace(); //shows you the error
        }


        System.out.println("jytyjrhjyrhtrhtyr");

//        ratio = numerator / denominator;
//        System.out.println("The answer is: "+ratio);
//
//        System.out.println("Done."); // Don't move this line
    }
}

// 1-2. What was output by the application when you executed it? --> The answer is: 2
                                                               //Done.
// 3-4. What "error" was generated by the application when you executed it? --> Exception in thread "main" java.lang.ArithmeticException: / by zero
// 3-4. Why was this "error" generated at run-time (rather than at compile-time)? --> because the code itself is correct, but the arithmetic execution is incorrect
// 5. What error is generated and why? --> variable ratio might not have been initialized; because ratio is not initialized in try block
// 6-7. What output was generated? --> Divide by 0
// 8. What output was generated? --> Divide by 0
                                    //java.lang.ArithmeticException: / by zero
                                            //	at Example1.main(Example1.java:22)
// 8. Did the application execute properly or not? --> yes because program did not fall


